#!/bin/bash

if [ -z "$FL_ROOT" ]; then
  case "$EUID" in
    0) root='/opt' ;;
    *) root='~'    ;;
  esac
  export FL_ROOT="$root/flight-direct"
fi

pushd $fd_dev_root >/dev/null
export LD_LIBRARY_PATH=$FL_ROOT/embedded/lib:$LD_LIBRARY_PATH
omnibus build flight-direct-dev
popd >/dev/null

