#!/bin/bash
# This script installs rvm and the gems using bundler
# It assumes nothing has already been setup, however hopefully this shouldn't
# make much of a difference
set -e
sudo yum install git -y -e0

# Installs rvm and bundler
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
curl -sSL https://get.rvm.io | bash -s 1.29.3 --ignore-dotfiles --ruby=2.5.1

# Manually adds sourcing rvm to the bashrc, this makes the behaviour
# a bit more predictable
if [[ $EUID -eq 0 ]]; then
  echo 'source /usr/local/rvm/scripts/rvm' >> ~/.bashrc
else
  echo 'source ~/.rvm/scripts/rvm' >> ~/.bashrc
fi
source ~/.bashrc

# Installs the gems
gem install bundler

# Installs the development gems
pushd $fd_dev_root >/dev/null
bundle install --without default --with development
popd >/dev/null

