#!/bin/bash

msg='Can not determine the flight direct install location'
: ${FL_ROOT?$msg}

pushd $fd_dev_root >/dev/null
rsync --update --no-perms --no-owner --no-group -rv \
      bin etc lib libexec scripts Gemfile* $FL_ROOT/
popd >/dev/null
