#!/bin/bash
#
# When "flight-direct" is installed (e.g. `yum install`), it will run this script.
# This script has been adapted from clusterware:
# https://raw.githubusercontent.com/alces-software/clusterware/064d7a6e7a2f8d2a3f1874415c0bd8ee429099f7/dist/profile/alces-clusterware.csh
#
# For an example repo using script hook-ins like this, see:
# https://github.com/scoutapp/omnibus-scout
#

echo "source /opt/flight-direct/etc/profile.sh" > /etc/profile.d/alces-flight-direct.sh

exit 0
